# Generated by Django 3.0.7 on 2020-06-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockDetail',
            fields=[
                ('block_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('block_id', models.IntegerField(blank=True, null=True)),
                ('block_detail_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('block_detail', models.TextField(blank=True, max_length=50000, null=True)),
                ('block_detail_status', models.BooleanField(blank=True, null=True)),
                ('block_detail_image', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('blog_author', models.CharField(blank=True, max_length=100, null=True)),
                ('blog_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('block_image', models.ImageField(upload_to='image')),
                ('block_status', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_status', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_parent_id', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('category_status', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('ship_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ship_address', models.CharField(blank=True, max_length=1000, null=True)),
                ('ship_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('order_status', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('order_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_quantity', models.IntegerField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_quantity', models.IntegerField(blank=True, null=True)),
                ('product_image', models.ImageField(upload_to='image')),
                ('product_image_1', models.ImageField(null=True, upload_to='image')),
                ('product_detail', models.TextField(blank=True, max_length=5000, null=True)),
                ('product_status', models.BooleanField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('image_path', models.ImageField(upload_to='image')),
                ('image_path_1', models.ImageField(null=True, upload_to='image')),
                ('image_path_2', models.ImageField(null=True, upload_to='image')),
                ('image_path_3', models.ImageField(null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('discount', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
